# Generated by Django 5.2 on 2025-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General Mechanic'), ('engine', 'Engine Specialist'), ('electrical', 'Electrical Systems'), ('brakes', 'Brakes & Suspension'), ('diagnostics', 'Diagnostics')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
