# Generated by Django 5.2 on 2025-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicetype_alter_job_mechanic_alter_job_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_license',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
