# Generated by Django 5.2 on 2025-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_servicerequest_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_type',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='description',
            new_name='additional_notes',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
