# Generated by Django 5.2 on 2025-05-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_servicerequest_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Hand'), ('online', 'Online Payment')], default='cash', max_length=20),
        ),
    ]
