# Generated by Django 5.2 on 2025-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_invoice_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
