# Generated by Django 5.2 on 2025-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_servicerequest_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
