# Generated by Django 5.2 on 2025-05-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_servicerequest_otp_servicerequest_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
