# Generated by Django 5.2 on 2025-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='mobile_num',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
