# Generated by Django 5.2 on 2025-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_servicerequest_location_servicerequest_mobile_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='mobile_num',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
