# Generated by Django 5.2 on 2025-06-08 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_servicerequest_mobile_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +91 9876543210', regex='^\\+\\d{1,3}\\s?\\d{10}$')]),
        ),
    ]
