# Generated by Django 5.2 on 2025-06-08 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_job_comments_alter_servicerequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +<country code> <10 digits>, e.g., +91 9876543210', regex='^\\+\\d{1,3}\\s?\\d{10}$')]),
        ),
    ]
